server:
  port: 8082

spring:
  application:
    name: order-api
  datasource:
    url: ${ORDER_DB_URL:jdbc:mysql://localhost:3306/orderdb}
#    url: orderdb:3306
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#    bootstrap-servers: kafka:29092
    topic: order-event
springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    tags:
      application: order-api
