name: Build and Test

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 트리거
  pull_request:
    branches:
      - main  # main 브랜치로의 PR 발생 시 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Docker in Docker (DinD) 설정
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 9090:9090
          - 3005:3005
          - 23306:3306
          - 22181:12181
          - 29092:19092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock  # Docker socket 마운트

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start containers with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests 
        run: |
          curl -I http://localhost:8082/orders | grep "200 OK"

      - name: Shutdown containers
        run: |
          docker-compose down

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # main 브랜치일 때만 배포

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production (optional)
        run: |
          # 배포 관련 명령어 (예: 서버에 SSH 접속하여 `docker-compose up -d` 실행)
          echo "Deploying to production..."
